# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ds-build-and-test

on:
  push:
  pull_request:

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  SRC_DIR: .

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build ${{ env.SRC_DIR }}/DelegationSharedLibrary --configuration ${{ env.CONFIGURIATION}} --no-restore
        dotnet build ${{ env.SRC_DIR }}/DelegationStation --configuration ${{ env.CONFIGURIATION}} --no-restore
        dotnet build ${{ env.SRC_DIR }}/UpdateDevices --configuration ${{ env.CONFIGURIATION}} --no-restore
        # dotnet build ${{ env.SRC_DIR }}/DelegationStationTests --configuration ${{ env.CONFIGURIATION}} --no-restore
      
   # - name: Test
   #   run: dotnet test --no-build --verbosity normal
